package api

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/prejudice-studio/twilight/internal/security"
	"github.com/prejudice-studio/twilight/internal/store"
	"github.com/prejudice-studio/twilight/internal/validate"
)

func (a *App) handleAdminUsers(w http.ResponseWriter, r *http.Request, _ Params) {
	page := max(1, queryInt(r, "page", 1))
	perPage := clamp(queryInt(r, "per_page", 20), 1, 100)
	query := r.URL.Query()
	filter := adminUserListFilter{
		roleFilter:        query.Get("role"),
		hasRole:           query.Get("role") != "",
		activeFilter:      query.Get("active"),
		hasActive:         query.Get("active") != "",
		strictQueryActive: true,
		embyFilter:        strings.ToLower(strings.TrimSpace(query.Get("emby"))),
		embyStatusFilter:  strings.ToLower(strings.TrimSpace(query.Get("emby_status"))),
		emailFilter:       strings.ToLower(strings.TrimSpace(query.Get("email_status"))),
		search:            strings.ToLower(strings.TrimSpace(query.Get("search"))),
		now:               time.Now().Unix(),
	}
	// 只在筛选中保留匹配用户（无 limit，与旧 ListUsers 语义一致）。排序时继续使用
	// 轻量的 store.User，分页后才构造公开 DTO；大用户量下不能为页外用户创建完整 map。
	matched := a.store().UsersMatching(0, func(u store.User) bool {
		return adminUserMatchesListFilters(u, filter)
	})
	sortUsers(matched, query.Get("sort"))
	total := len(matched)
	pageUsers := paginate(matched, page, perPage)
	items := make([]map[string]any, 0, len(pageUsers))
	for _, u := range pageUsers {
		items = append(items, publicUserAt(u, filter.now))
	}
	ok(w, "OK", map[string]any{"users": items, "total": total, "page": page, "per_page": perPage, "pages": pages(total, perPage)})
}

func (a *App) handleAdminCreateUser(w http.ResponseWriter, r *http.Request, _ Params) {
	payload := decodeMap(r)
	username := strings.TrimSpace(stringValue(payload, "username"))
	if err := validate.ValidateUsername(username); err != nil {
		failWithCode(w, http.StatusBadRequest, ErrUsernameInvalid, err.Error())
		return
	}
	if _, exists := a.store().FindUserByUsername(username); exists {
		failWithCode(w, http.StatusConflict, ErrUsernameTaken, "用户名已被占用，请换一个用户名")
		return
	}
	role := store.RoleNormal
	if rawRole, ok := payload["role"]; ok {
		parsed, valid := normalizeRoleValue(rawRole)
		if !valid || parsed == store.RoleUnrecognized {
			failWithCode(w, http.StatusBadRequest, ErrBadRequest, "role 取值非法")
			return
		}
		role = parsed
	}
	telegramID := int64(intValue(payload, "telegram_id", 0))
	if telegramID < 0 {
		failWithCode(w, http.StatusBadRequest, ErrTGBindTGIDInvalid, "Telegram ID 无效")
		return
	}
	if telegramID != 0 {
		if existing, okUser := a.store().FindUserByTelegramID(telegramID); okUser {
			failWithCode(w, http.StatusConflict, ErrTGAlreadyBound, "该 Telegram 已绑定到账号 "+existing.Username)
			return
		}
	}
	password := stringValue(payload, "password")
	autoGenerated := password == ""
	if autoGenerated {
		password = "Twilight-" + randomCode(generatedPasswordHexLen)
	} else if err := validate.ValidatePasswordStrength(password); err != nil {
		failWithCode(w, http.StatusBadRequest, ErrPasswordWeak, err.Error())
		return
	}
	hash, err := security.HashPassword(password)
	if err != nil {
		failWithCode(w, http.StatusInternalServerError, ErrPasswordHashFailed, "密码处理失败")
		return
	}
	expiredAt := numeric(payload["expired_at"])
	if _, ok := payload["days"]; ok {
		days := intValue(payload, "days", -1)
		if days < 0 {
			expiredAt = permanentExpiryUnix
		} else {
			expiredAt = time.Now().AddDate(0, 0, days).Unix()
		}
	}
	if expiryIsPermanent(expiredAt) {
		expiredAt = permanentExpiryUnix
	}
	if email := stringValue(payload, "email"); email != "" {
		if err := validate.ValidateEmailFormat(email); err != nil {
			failWithCode(w, http.StatusBadRequest, ErrEmailInvalid, err.Error())
			return
		}
	}
	createdUser, err := a.store().CreateUser(store.User{
		Username:         username,
		Email:            stringValue(payload, "email"),
		PasswordHash:     hash,
		Role:             role,
		ExpiredAt:        expiredAt,
		TelegramID:       telegramID,
		TelegramUsername: strings.TrimPrefix(strings.TrimSpace(stringValue(payload, "telegram_username")), "@"),
	})
	if errors.Is(err, store.ErrConflict) {
		failWithCode(w, http.StatusConflict, ErrUsernameTaken, "用户名或 Telegram 已被占用")
		return
	}
	if statusFromError(w, err) {
		return
	}
	a.audit(r, "admin_create_user", "admin", createdUser.UID, map[string]any{"username": createdUser.Username})
	created(w, "Web account created", map[string]any{"user": publicUser(createdUser), "password": password, "auto_generated": autoGenerated})
}

func (a *App) handleAdminUser(w http.ResponseWriter, r *http.Request, params Params) {
	u, okUser := a.userFromPath(w, params, "uid")
	if !okUser {
		return
	}
	ok(w, "OK", publicUser(u))
}

func (a *App) handleAdminUpdateUser(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	payload := decodeMap(r)
	// 在进入 store.UpdateUser 之前先把字段校验跑完：role 必须在已知集合内，
	// username 必须通过 validate.ValidateUsername，否则会出现：
	//   - admin 给用户写入未知 role（如 99），前端 roleName 落到"未识别"，
	//     该用户无法被任何鉴权分支处理；
	//   - admin 改写的 username 包含禁止字符 / 长度越界，导致用户后续无法登录。
	var (
		hasRole     bool
		desiredRole int
	)
	if rawRole, ok := payload["role"]; ok {
		role, valid := normalizeRoleValue(rawRole)
		if !valid {
			failWithCode(w, http.StatusBadRequest, ErrBadRequest, "role 取值非法")
			return
		}
		hasRole = true
		desiredRole = role
	}
	if rawUsername, ok := payload["username"]; ok {
		if username, isStr := rawUsername.(string); isStr && username != "" {
			if err := validate.ValidateUsername(username); err != nil {
				failWithCode(w, http.StatusBadRequest, ErrUsernameInvalid, err.Error())
				return
			}
		}
	}
	if rawEmail, ok := payload["email"]; ok {
		if email, isStr := rawEmail.(string); isStr && email != "" {
			if err := validate.ValidateEmailFormat(email); err != nil {
				failWithCode(w, http.StatusBadRequest, ErrEmailInvalid, err.Error())
				return
			}
		}
	}
	// active 字段必须走 SetUserActiveAtomic：直接在 UpdateUser 闭包里
	// 写 u.Active = false 会绕过 last-admin 守卫，最后一名 active admin 会被
	// 任何带 active=false 的 PATCH 静默禁用，等价于 self-disable 自残。
	currentUID := current(r).User.UID
	hasActive := false
	desiredActive := true
	if raw, ok := payload["active"]; ok {
		hasActive = true
		switch v := raw.(type) {
		case bool:
			desiredActive = v
		case string:
			desiredActive = strings.EqualFold(strings.TrimSpace(v), "true")
		case float64:
			desiredActive = v != 0
		default:
			failWithCode(w, http.StatusBadRequest, ErrBadRequest, "active 取值非法")
			return
		}
		if !desiredActive && uid == currentUID {
			failWithCode(w, http.StatusForbidden, ErrUserProtected, "无法禁用自己的账号")
			return
		}
	}
	// role 写入走 store.SetUserRoleAtomic：在同一把锁里做"读取目标当前 role +
	// 计数 active admin + 写入"，避免两个 admin 并发降级两个不同 admin 时
	// 同时通过 last-admin 校验导致 0 admin。其它字段再走 UpdateUser 闭包。
	if hasRole {
		if _, err := a.store().SetUserRoleAtomic(uid, desiredRole); err != nil {
			if errors.Is(err, store.ErrLastAdmin) {
				failWithCode(w, http.StatusConflict, ErrAdminLastAdminProtected, "无法移除最后一个管理员的权限，系统至少需要一个管理员")
				return
			}
			if statusFromError(w, err) {
				return
			}
		}
	}
	embySyncFailed := false
	if hasActive {
		updated, err := a.store().SetUserActiveAtomic(uid, desiredActive)
		if err != nil {
			if errors.Is(err, store.ErrLastAdmin) {
				failWithCode(w, http.StatusConflict, ErrAdminLastAdminProtected, "无法禁用最后一个管理员，系统至少需要一个管理员")
				return
			}
			if statusFromError(w, err) {
				return
			}
		}
		if !desiredActive {
			if _, syncErr := a.disableRemoteEmbyForWebState(r.Context(), updated); syncErr != nil {
				embySyncFailed = true
			}
		}
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if username := stringValue(payload, "username"); username != "" {
			u.Username = username
		}
		if email := stringValue(payload, "email"); email != "" {
			u.Email = email
		}
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	data := publicUser(u)
	if embySyncFailed {
		data["emby_sync_failed"] = true
	}
	a.audit(r, "update_user", "admin", uid, map[string]any{
		"has_role": hasRole, "has_active": hasActive,
	})
	ok(w, "user updated", data)
}

// normalizeRoleValue 把任意 JSON 数值收成已知 role 整数。
// 仅 RoleAdmin / RoleNormal / RoleWhitelist / RoleUnrecognized 视为合法。
// 用于 admin update / set-role 等所有写 user.Role 的入口，避免持久化未知值。
func normalizeRoleValue(v any) (int, bool) {
	var role int
	switch n := v.(type) {
	case float64:
		role = int(n)
	case int:
		role = n
	case int64:
		role = int(n)
	case string:
		parsed, err := strconv.Atoi(strings.TrimSpace(n))
		if err != nil {
			return 0, false
		}
		role = parsed
	default:
		return 0, false
	}
	switch role {
	case store.RoleAdmin, store.RoleNormal, store.RoleWhitelist, store.RoleUnrecognized:
		return role, true
	default:
		return 0, false
	}
}

func (a *App) handleAdminDeleteUser(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	if uid == current(r).User.UID {
		failWithCode(w, http.StatusForbidden, ErrUserProtected, "cannot delete current admin")
		return
	}
	payload := decodeMap(r)
	mode := firstNonEmpty(stringValue(payload, "mode"), "local_only")
	if mode != "local_only" && mode != "with_emby" && mode != "emby_only" {
		failWithCode(w, http.StatusBadRequest, ErrBadRequest, "mode 必须是 local_only、with_emby 或 emby_only")
		return
	}
	depth := intValue(payload, "cascade_depth", queryInt(r, "cascade_depth", 1))
	deleted := []int64{}
	skipped := []map[string]any{}
	failed := []map[string]any{}
	for _, targetUID := range a.collectCascadeUIDs(uid, depth) {
		target, okUser := a.store().User(targetUID)
		if !okUser {
			skipped = append(skipped, map[string]any{"uid": targetUID, "reason": "not_found"})
			continue
		}
		if a.userIsProtected(target) {
			skipped = append(skipped, map[string]any{"uid": targetUID, "reason": a.protectedUserReason(target)})
			continue
		}
		if mode == "emby_only" {
			if target.EmbyID != "" {
				if !a.embyConfigured() {
					failed = append(failed, map[string]any{"uid": targetUID, "reason": "delete_emby: emby not configured"})
					continue
				}
				if err := a.embyDelete(r.Context(), "/Users/"+urlPathEscape(target.EmbyID)); err != nil && !strings.Contains(err.Error(), "remote status 404") {
					failed = append(failed, map[string]any{"uid": targetUID, "reason": "delete_emby: " + err.Error()})
					continue
				}
			}
			_, err := a.store().UpdateUser(targetUID, func(u *store.User) error { u.EmbyID = ""; u.EmbyUsername = ""; return nil })
			if err != nil {
				failed = append(failed, map[string]any{"uid": targetUID, "reason": err.Error()})
			} else {
				a.store().ClearEmbyGrantForUnboundUsers([]int64{targetUID})
				deleted = append(deleted, targetUID)
			}
			continue
		}
		if mode == "with_emby" && target.EmbyID != "" {
			if !a.embyConfigured() {
				failed = append(failed, map[string]any{"uid": targetUID, "reason": "delete_emby: emby not configured"})
				continue
			}
			if err := a.embyDelete(r.Context(), "/Users/"+urlPathEscape(target.EmbyID)); err != nil && !strings.Contains(err.Error(), "remote status 404") {
				failed = append(failed, map[string]any{"uid": targetUID, "reason": "delete_emby: " + err.Error()})
				continue
			}
		}
		if err := a.deleteLocalUser(context.WithoutCancel(r.Context()), target); err != nil {
			failed = append(failed, map[string]any{"uid": targetUID, "reason": err.Error()})
			continue
		}
		deleted = append(deleted, targetUID)
	}
	// 审计日志
	if len(deleted) > 0 {
		a.audit(r, "delete_user", "admin", uid, map[string]any{"deleted": deleted, "mode": mode, "cascade_depth": depth})
	}
	ok(w, "users deleted", map[string]any{"deleted": deleted, "skipped": skipped, "failed": failed, "mode": mode, "cascade_depth": depth})
}

func (a *App) handleAdminToggleUser(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	enable := strings.HasSuffix(r.URL.Path, "/enable")
	currentUID := current(r).User.UID
	// admin 不允许 disable 自己：自残会让 admin 立即丢失 active 状态、踢自己下线，
	// 同时绕开 store.SetUserActiveAtomic 的"剩余 active admin >= 1" 兜底。
	if !enable && uid == currentUID {
		failWithCode(w, http.StatusForbidden, ErrUserProtected, "无法禁用自己的账号")
		return
	}
	if target, okUser := a.store().User(uid); okUser && a.userIsProtected(target) && target.UID != currentUID {
		failWithCode(w, http.StatusForbidden, ErrUserProtected, "cannot operate on protected user")
		return
	}
	payload := decodeMap(r)
	depth := intValue(payload, "cascade_depth", queryInt(r, "cascade_depth", 1))
	// 禁用理由可选，仅在禁用方向有意义，超长截断防止审计 detail 膨胀。
	reason := strings.TrimSpace(stringValue(payload, "reason"))
	if len(reason) > 200 {
		reason = reason[:200]
	}
	affected := []int64{}
	skipped := []map[string]any{}
	failed := []map[string]any{}
	embyFailed := []map[string]any{}
	for _, targetUID := range a.collectCascadeUIDs(uid, depth) {
		if target, okUser := a.store().User(targetUID); okUser && a.userIsProtected(target) && target.UID != currentUID {
			skipped = append(skipped, map[string]any{"uid": targetUID, "reason": a.protectedUserReason(target)})
			continue
		}
		// 走 SetUserActiveAtomic：禁用最后一个 active admin 时返回 ErrLastAdmin，
		// 在级联场景下被记入 skipped 而不是悄悄通过。
		updated, err := a.store().SetUserActiveAtomic(targetUID, enable)
		if err != nil {
			if errors.Is(err, store.ErrLastAdmin) {
				skipped = append(skipped, map[string]any{"uid": targetUID, "reason": "last_admin"})
				continue
			}
			failed = append(failed, map[string]any{"uid": targetUID, "reason": err.Error()})
			continue
		}
		if !enable {
			// Emby 同步失败不阻断本地禁用，但记录到响应让管理员知晓。
			if _, syncErr := a.disableRemoteEmbyForWebState(r.Context(), updated); syncErr != nil {
				embyFailed = append(embyFailed, map[string]any{"uid": targetUID, "reason": syncErr.Error()})
			}
		}
		affected = append(affected, targetUID)
	}
	u, _ := a.store().User(uid)
	resp := map[string]any{"user": publicUser(u), "active": enable, "affected": affected, "skipped": skipped, "failed": failed, "cascade_depth": depth, "enable": enable}
	if len(embyFailed) > 0 {
		resp["emby_failed"] = embyFailed
	}
	// 审计日志
	if len(affected) > 0 {
		action := "disable_user"
		if enable {
			action = "enable_user"
		}
		detail := map[string]any{"affected": affected, "cascade_depth": depth}
		// 仅禁用方向记录理由，避免给启用操作附带无意义的旧理由。
		if !enable && reason != "" {
			detail["reason"] = reason
		}
		a.audit(r, action, "admin", uid, detail)
	}
	ok(w, "用户状态已更新", resp)
}

// handleAdminToggleEmby 单独启停用户的 Emby 账号，不改动其 Web 账号状态。
// 与「禁用 Web 账号顺带关停 Emby」相反：管理员有时只想停掉某人的 Emby 观看权限，
// 但保留其网页端登录（看公告、改资料、续费）。守卫与 Telegram 面板的同名操作对齐：
// 受保护账号不可操作；未绑定 Emby / 未配置 Emby 直接拒绝；启用方向必须满足
// embyShouldEnableUser（Web 处于 active 且未过期），不得绕过有效期把 Emby 重新放开。
func (a *App) handleAdminToggleEmby(w http.ResponseWriter, r *http.Request, params Params) {
	enable := strings.HasSuffix(r.URL.Path, "/enable")
	target, okUser := a.userFromPath(w, params, "uid")
	if !okUser {
		return
	}
	if a.userIsProtected(target) {
		failWithCode(w, http.StatusForbidden, ErrUserProtected, "受保护账号禁止单独修改 Emby 状态")
		return
	}
	if target.EmbyID == "" {
		failWithCode(w, http.StatusBadRequest, ErrEmbyAccountUnlinked, "目标用户未绑定 Emby 账号")
		return
	}
	if !a.embyConfigured() {
		failWithCode(w, http.StatusBadGateway, ErrEmbyNotConfigured, "Emby URL 或 API Token 未配置")
		return
	}
	if enable && !a.embyShouldEnableUser(target) {
		failWithCode(w, http.StatusConflict, ErrConflict, "Web 账号已禁用或已过期，禁止绕过有效期直接启用 Emby")
		return
	}
	// 禁用理由可选，仅在禁用方向有意义，超长截断防止审计 detail 膨胀。
	payload := decodeMap(r)
	reason := strings.TrimSpace(stringValue(payload, "reason"))
	if len(reason) > 200 {
		reason = reason[:200]
	}
	if err := a.embyApplyEnabledState(r.Context(), target.UID, target.EmbyID, enable); err != nil {
		failWithCode(w, http.StatusBadGateway, ErrEmbyDisableFailed, "Emby 状态更新失败")
		return
	}
	action := "admin_disable_emby"
	if enable {
		action = "admin_enable_emby"
	}
	var detail map[string]any
	// 仅禁用方向记录理由，避免给启用操作附带无意义的旧理由。
	if !enable && reason != "" {
		detail = map[string]any{"reason": reason}
	}
	a.audit(r, action, "admin", target.UID, detail)
	ok(w, "Emby 状态已更新", map[string]any{"uid": target.UID, "emby_enabled": enable})
}

func (a *App) handleAdminUnbindEmby(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	target, okUser := a.store().User(uid)
	if !okUser {
		failWithCode(w, http.StatusNotFound, ErrUserNotFound, userNotFoundMessage)
		return
	}
	embyID := target.EmbyID
	remoteDisabled, proceed := a.disableRemoteEmbyForUnbind(w, r, embyID)
	if !proceed {
		return
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if embyID != "" && u.EmbyID != "" && u.EmbyID != embyID {
			return store.ErrConflict
		}
		u.EmbyID = ""
		u.EmbyUsername = ""
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	data := publicUser(u)
	data["remote_emby_disabled"] = remoteDisabled
	data["old_emby_id"] = embyID
	ok(w, "Emby unbound", data)
}

func (a *App) handleAdminForceUnbind(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	target, okUser := a.store().User(uid)
	if !okUser {
		failWithCode(w, http.StatusNotFound, ErrUserNotFound, userNotFoundMessage)
		return
	}
	scope := strings.ToLower(stringValue(decodeMap(r), "scope"))
	if scope == "" {
		scope = "both"
	}
	if scope != "telegram" && scope != "emby" && scope != "both" {
		failWithCode(w, http.StatusBadRequest, ErrBadRequest, "scope 必须是 telegram、emby 或 both")
		return
	}
	unbindTelegram := scope == "telegram" || scope == "both"
	unbindEmby := scope == "emby" || scope == "both"
	oldTelegramID := target.TelegramID
	oldEmbyID := target.EmbyID
	remoteDisabled := false
	if unbindEmby {
		var proceed bool
		remoteDisabled, proceed = a.disableRemoteEmbyForUnbind(w, r, oldEmbyID)
		if !proceed {
			return
		}
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if unbindTelegram {
			u.TelegramID = 0
			u.TelegramUsername = ""
		}
		if unbindEmby {
			if oldEmbyID != "" && u.EmbyID != "" && u.EmbyID != oldEmbyID {
				return store.ErrConflict
			}
			u.EmbyID = ""
			u.EmbyUsername = ""
		}
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	if unbindTelegram {
		a.cleanupUserTelegramResidue(uid, oldTelegramID)
	}
	changed := []string{}
	if unbindTelegram && oldTelegramID != 0 {
		changed = append(changed, "telegram")
	}
	if unbindEmby && oldEmbyID != "" {
		changed = append(changed, "emby")
	}
	a.audit(r, "admin_force_unbind", "admin", uid, map[string]any{"changed": changed})
	ok(w, "unbound", map[string]any{
		"changed":              changed,
		"changed_any":          len(changed) > 0,
		"old":                  map[string]any{"telegram_id": nullableInt(oldTelegramID), "emby_id": emptyNil(oldEmbyID)},
		"remote_emby_disabled": remoteDisabled,
		"user":                 publicUser(u),
	})
}

func (a *App) handleRegistrationQueueClear(w http.ResponseWriter, r *http.Request, params Params) {
	if params["uid"] != "" {
		uid, _ := int64Param(params, "uid")
		u, err := a.store().UpdateUser(uid, func(u *store.User) error { u.PendingEmby = false; u.PendingEmbyDays = nil; return nil })
		if statusFromError(w, err) {
			return
		}
		ok(w, "注册队列状态已清理", map[string]any{"uid": uid, "user": publicUser(u)})
		return
	}
	payload := decodeMap(r)
	dryRun := boolValue(payload, "dry_run", true)
	confirm := stringValue(payload, "confirm")
	candidates := []int64{}
	for _, u := range a.store().ListUsers() {
		if u.PendingEmby {
			candidates = append(candidates, u.UID)
		}
	}
	if dryRun || confirm != "CLEAR_REGISTRATION_QUEUE" {
		ok(w, "dry-run", map[string]any{"dry_run": true, "candidates": candidates, "count": len(candidates), "confirm_required": "CLEAR_REGISTRATION_QUEUE"})
		return
	}
	updated := 0
	failed := []int64{}
	for _, uid := range candidates {
		if _, err := a.store().UpdateUser(uid, func(u *store.User) error { u.PendingEmby = false; u.PendingEmbyDays = nil; return nil }); err != nil {
			failed = append(failed, uid)
			continue
		}
		updated++
	}
	if len(failed) > 0 {
		failWithCode(w, http.StatusInternalServerError, ErrAdminQueueClearPartial, "部分注册队列状态清理失败")
		return
	}
	ok(w, "registration queue cleaned", map[string]any{"updated": updated, "uids": candidates})
}

func (a *App) handleRegistrationEntitlement(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	days := normalizeRegCodeDays(intValue(decodeMap(r), "days", a.cfg().InviteDefaultDays))
	if days < -1 || days > 3650 {
		failWithCode(w, http.StatusBadRequest, ErrAdminDaysOutOfRange, "days 超出允许范围")
		return
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if u.EmbyID != "" {
			return store.ErrConflict
		}
		u.PendingEmby = true
		u.PendingEmbyDays = &days
		markRegistrationGrant(u, registrationSourceAdminGrant, "")
		if u.Role == store.RoleUnrecognized {
			u.Role = store.RoleNormal
		}
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	ok(w, "Emby access granted", map[string]any{"uid": uid, "days": days, "user": publicUser(u)})
}

func (a *App) handleRegistrationEntitlementBulk(w http.ResponseWriter, r *http.Request, _ Params) {
	payload := decodeMap(r)
	dryRun := boolValue(payload, "dry_run", true)
	confirm := stringValue(payload, "confirm")
	days := normalizeRegCodeDays(intValue(payload, "days", a.cfg().InviteDefaultDays))
	if days < -1 || days > 3650 {
		failWithCode(w, http.StatusBadRequest, ErrAdminDaysOutOfRange, "days 超出允许范围")
		return
	}
	candidates := []int64{}
	for _, u := range a.store().ListUsers() {
		if u.PendingEmby && u.EmbyID == "" && u.Active {
			candidates = append(candidates, u.UID)
		}
	}
	if dryRun || confirm != "GRANT_AND_CLEAR_REGISTRATION_QUEUE" {
		ok(w, "dry-run", map[string]any{"dry_run": true, "candidates": candidates, "count": len(candidates), "confirm_required": "GRANT_AND_CLEAR_REGISTRATION_QUEUE"})
		return
	}
	updated := 0
	failed := []int64{}
	for _, uid := range candidates {
		if _, err := a.store().UpdateUser(uid, func(u *store.User) error {
			u.PendingEmby = true
			u.PendingEmbyDays = &days
			markRegistrationGrant(u, registrationSourceAdminGrant, "")
			if u.Role == store.RoleUnrecognized {
				u.Role = store.RoleNormal
			}
			return nil
		}); err != nil {
			failed = append(failed, uid)
			continue
		}
		updated++
	}
	if len(failed) > 0 {
		failWithCode(w, http.StatusInternalServerError, ErrAdminEntitlementPartial, "部分 Emby 注册资格发放失败")
		return
	}
	ok(w, "batch access granted", map[string]any{"updated": updated, "uids": candidates, "days": days})
}

func (a *App) handleSyncBindings(w http.ResponseWriter, r *http.Request, _ Params) {
	body := decodeMap(r)
	targetUID := int64(numeric(body["uid"]))
	users := a.store().ListUsers()
	if targetUID > 0 {
		if u, ok := a.store().User(targetUID); ok {
			users = []store.User{u}
		} else {
			users = nil
		}
	}
	seenTG := map[int64]int64{}
	duplicates := []map[string]any{}
	missingEmby := []int64{}
	checked := 0
	for _, u := range users {
		checked++
		if u.TelegramID != 0 {
			if previous, ok := seenTG[u.TelegramID]; ok {
				duplicates = append(duplicates, map[string]any{"telegram_id": u.TelegramID, "uids": []int64{previous, u.UID}})
			} else {
				seenTG[u.TelegramID] = u.UID
			}
		}
		if u.EmbyID != "" && a.cfg().EmbyURL != "" {
			var remote map[string]any
			if err := a.embyGet(r.Context(), "/Users/"+urlPathEscape(u.EmbyID), &remote); err != nil {
				missingEmby = append(missingEmby, u.UID)
			}
		}
	}
	ok(w, "binding sync checked", map[string]any{"matched": checked, "telegram_duplicates": duplicates, "emby_missing": missingEmby, "repaired": 0, "synced": checked - len(missingEmby), "failed": len(missingEmby)})
}

func (a *App) handleKickUser(w http.ResponseWriter, r *http.Request, params Params) {
	u, okUser := a.userFromPath(w, params, "uid")
	if !okUser {
		return
	}
	kicked := a.kickEmbySessions(r.Context(), u.EmbyID)
	ok(w, "会话踢出完成", map[string]any{"kicked_count": kicked})
}

func (a *App) handleAdminRenewUser(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	payload := decodeMap(r)
	days := int64(normalizeRegCodeDays(intValue(payload, "days", 30)))
	if expiredAt := numeric(payload["expired_at"]); expiredAt < 0 || expiryIsPermanent(expiredAt) {
		days = -1
	}
	// 与 handleAdminSetUserExpiry / handleBatchRenewUsers / handleAdminBulkExpire
	// 对齐：正天数必须有上限。少了这道闸，base+days*86400 既可能因 days 巨大直接
	// 落进 permanentExpiryUnix 区间（静默把账号变永久），更大的值还会让 int64
	// 乘法溢出回绕成负数 → expiryIsPermanent 也判真。days<0 是显式永久路径，放行。
	if days > 36500 {
		failWithCode(w, http.StatusBadRequest, ErrBadRequest, "days 不能超过 36500")
		return
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if days < 0 {
			renewExpiryAndReactivate(u, permanentExpiryUnix)
			return nil
		}
		base := time.Now().Unix()
		if u.ExpiredAt > base {
			base = u.ExpiredAt
		}
		// admin renew 走统一助手：被 check_expired 自动禁用的账号在续费成功
		// 后必须自动恢复登录，否则 admin 续完看到用户报"账号被禁"再来一次
		// 手动 enable，这一步漏掉就违反 R62 不变量。
		renewExpiryAndReactivate(u, base+days*86400)
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	a.audit(r, "admin_renew_user", "admin", uid, map[string]any{"days": days})
	ok(w, "续期成功", publicUser(u))
}

// handleAdminSetUserExpiry 绝对式设置用户到期时间，区别于 handleAdminRenewUser 的
// 叠加续期：这里直接把 ExpiredAt 覆盖为「从现在起 N 天后」或「永久」，不读取旧值做
// base。它服务两条路由：
//   - /cancel-permanent：把永久号改成 N 天后到期。旧实现复用叠加式 renew，base 取
//     max(now, ExpiredAt)，而永久号的 ExpiredAt == permanentExpiryUnix（2534 年），
//     于是 base+days 依旧 >= permanentExpiryUnix → expiryIsPermanent 仍为真，"取消
//     永久"实际什么都没改。绝对式设置修掉这个静默失败。
//   - /set-expiry：管理员手动把任意用户的剩余到期时间设为精确值（覆盖，不叠加）。
//
// days < 0 或 permanent=true 或 expired_at 永久哨兵 → 设永久；否则 days 必须为正整数，
// 上限 36500（与批量续期对齐），避免溢出或意外落进永久区间。
func (a *App) handleAdminSetUserExpiry(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	payload := decodeMap(r)
	permanent := boolValue(payload, "permanent", false)
	if expiredAt := numeric(payload["expired_at"]); expiredAt < 0 || expiryIsPermanent(expiredAt) {
		permanent = true
	}
	rawDays := intValue(payload, "days", 0)
	if rawDays < 0 {
		permanent = true
	}
	if !permanent {
		if rawDays <= 0 {
			failWithCode(w, http.StatusBadRequest, ErrBadRequest, "days 必须为正整数，或选择永久")
			return
		}
		if rawDays > 36500 {
			failWithCode(w, http.StatusBadRequest, ErrBadRequest, "days 不能超过 36500")
			return
		}
	}
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if permanent {
			renewExpiryAndReactivate(u, permanentExpiryUnix)
			return nil
		}
		// 绝对式：始终以 now 为基准，覆盖旧到期时间（含永久哨兵）。
		renewExpiryAndReactivate(u, time.Now().Unix()+int64(rawDays)*86400)
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	a.audit(r, "admin_set_expiry", "admin", uid, map[string]any{"days": rawDays, "permanent": permanent})
	ok(w, "到期时间已更新", publicUser(u))
}

func (a *App) handleAdminResetPassword(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	if uid == 0 {
		uid = current(r).User.UID
	}
	body := decodeMap(r)
	scope := strings.ToLower(firstNonEmpty(stringValue(body, "scope"), "both"))
	if scope != "system" && scope != "emby" && scope != "both" {
		failWithCode(w, http.StatusBadRequest, ErrAdminPasswordResetScope, "invalid password reset scope")
		return
	}
	targetUser, okUser := a.store().User(uid)
	if !okUser {
		failWithCode(w, http.StatusNotFound, ErrUserNotFound, userNotFoundMessage)
		return
	}
	newPassword := stringValue(body, "password")
	autoGenerated := newPassword == ""
	if autoGenerated {
		// 与 handleGeneratedPassword 保持一致：≥128 bit 熵。
		newPassword = "Twilight-" + randomCode(generatedPasswordHexLen)
	} else if okPass, msg := validateStrongPassword(newPassword, "password"); !okPass {
		failWithCode(w, http.StatusBadRequest, ErrPasswordWeak, msg)
		return
	}
	if (scope == "emby" || scope == "both") && targetUser.EmbyID == "" {
		// 旧实现里 scope=both 在 EmbyID 空时会"静默降级为 system"，前端无法察觉
		// 这次写入并未触达 Emby。改为返回 409 让前端显式选择"仅系统密码"或先绑 Emby。
		failWithCode(w, http.StatusConflict, ErrEmbyAccountUnlinked, "user has no linked Emby account; choose scope=system to reset only the system password")
		return
	}
	if scope == "emby" || scope == "both" {
		if err := a.embySetPassword(r.Context(), targetUser.EmbyID, newPassword); err != nil {
			failWithCode(w, http.StatusBadGateway, ErrAdminEmbyPasswordReset, "failed to reset Emby password")
			return
		}
	}
	if scope == "system" || scope == "both" {
		hashValue, err := security.HashPassword(newPassword)
		if err != nil {
			failWithCode(w, http.StatusInternalServerError, ErrPasswordHashFailed, "password processing failed")
			return
		}
		if _, updateErr := a.store().UpdateUser(uid, func(u *store.User) error { u.PasswordHash = hashValue; return nil }); updateErr != nil {
			statusFromError(w, updateErr)
			return
		}
		// 写完新密码必须立即吊销目标用户的所有会话：admin "重置密码" 的核心
		// 用途就是止血账号接管，旧实现却没踢 cookie，被盗 token 在 SessionTTL
		// 内仍然有效；与 handleAdminLogoutUser 保持一致，写入即吊销。
		a.sessions().DeleteUser(r.Context(), uid)
	}
	a.audit(r, "admin_reset_password", "admin", uid, map[string]any{"scope": scope, "auto_generated": autoGenerated})
	ok(w, "password reset", map[string]any{"scope": scope, "new_password": newPassword, "auto_generated": autoGenerated})
}

func (a *App) handleAdminEmbyForceSetPassword(w http.ResponseWriter, r *http.Request, _ Params) {
	if !a.embyConfigured() {
		failWithCode(w, http.StatusBadGateway, ErrEmbyNotConfigured, "Emby URL or API Token not configured")
		return
	}
	body := decodeMap(r)
	embyUsername := strings.TrimSpace(stringValue(body, "emby_username"))
	if embyUsername == "" {
		failWithCode(w, http.StatusBadRequest, ErrInvalidPayload, "emby_username is required")
		return
	}
	remoteUser, found, err := a.embyUserByName(r.Context(), embyUsername)
	if err != nil {
		failWithCode(w, http.StatusBadGateway, ErrEmbyNotConfigured, "failed to look up Emby user")
		return
	}
	if !found {
		failWithCode(w, http.StatusNotFound, ErrUserNotFound, "Emby user not found")
		return
	}
	embyID := asString(remoteUser["Id"])
	if embyID == "" {
		failWithCode(w, http.StatusInternalServerError, ErrInternal, "Emby returned empty user ID")
		return
	}
	newPassword := stringValue(body, "new_password")
	autoGenerated := newPassword == ""
	if autoGenerated {
		newPassword = "Twilight-" + randomCode(generatedPasswordHexLen)
	} else if okPass, msg := validateStrongPassword(newPassword, "new_password"); !okPass {
		failWithCode(w, http.StatusBadRequest, ErrPasswordWeak, msg)
		return
	}
	if err := a.embySetPassword(r.Context(), embyID, newPassword); err != nil {
		failWithCode(w, http.StatusBadGateway, ErrAdminEmbyPasswordReset, "failed to reset Emby password")
		return
	}
	linkedLocal := false
	for _, u := range a.store().ListUsers() {
		if u.EmbyID == embyID {
			hashValue, hashErr := security.HashPassword(newPassword)
			if hashErr == nil {
				_, _ = a.store().UpdateUser(u.UID, func(user *store.User) error {
					user.PasswordHash = hashValue
					return nil
				})
				a.sessions().DeleteUser(r.Context(), u.UID)
				a.audit(r, "admin_force_set_emby_password", "admin", u.UID, map[string]any{
					"emby_id":        embyID,
					"emby_username":  embyUsername,
					"auto_generated": autoGenerated,
				})
				linkedLocal = true
			}
			break
		}
	}
	if !linkedLocal {
		a.audit(r, "admin_force_set_emby_password", "admin", 0, map[string]any{
			"emby_id":        embyID,
			"emby_username":  embyUsername,
			"auto_generated": autoGenerated,
		})
	}
	ok(w, "password reset", map[string]any{
		"emby_id":           embyID,
		"emby_username":     embyUsername,
		"linked_local_user": linkedLocal,
		"new_password":      newPassword,
	})
}

func (a *App) handleAdminSetRole(w http.ResponseWriter, r *http.Request, params Params) {
	if requireAdmin(w, r) {
		return
	}
	uid, _ := int64Param(params, "uid")
	payload := decodeMap(r)
	role := store.RoleNormal
	if boolValue(payload, "is_admin", boolValue(payload, "admin", false)) {
		role = store.RoleAdmin
	}
	// SetUserRoleAtomic 在同一把写锁内做 last-admin 计数 + 写入。
	// 旧实现把 ListUsers 计数与 UpdateUser 闭包分两段执行，并发降级两个不同 admin
	// 时各自看到 adminCount=2 都通过校验，事后剩 0 admin。
	u, err := a.store().SetUserRoleAtomic(uid, role)
	if err != nil {
		if errors.Is(err, store.ErrLastAdmin) {
			failWithCode(w, http.StatusConflict, ErrAdminLastAdminProtected, "无法移除最后一个管理员的权限，系统至少需要一个管理员")
			return
		}
		if statusFromError(w, err) {
			return
		}
	}
	a.audit(r, "set_role", "admin", uid, map[string]any{
		"new_role": role,
	})
	ok(w, "role updated", publicUser(u))
}

func (a *App) handleAdminUnbindTelegram(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	old := int64(0)
	u, err := a.store().UpdateUser(uid, func(u *store.User) error {
		if u.Role == store.RoleAdmin && u.UID != current(r).User.UID {
			return store.ErrConflict
		}
		old = u.TelegramID
		u.TelegramID = 0
		u.TelegramUsername = ""
		return nil
	})
	if statusFromError(w, err) {
		return
	}
	a.cleanupUserTelegramResidue(uid, old)
	a.audit(r, "admin_unbind_telegram", "admin", uid, map[string]any{"old_telegram_id": old})
	ok(w, "Telegram unbound", map[string]any{"uid": u.UID, "username": u.Username, "old_telegram_id": old})
}

func (a *App) handleAdminBindTelegram(w http.ResponseWriter, r *http.Request, params Params) {
	uid, _ := int64Param(params, "uid")
	payload := decodeMap(r)
	tgid := int64(intValue(payload, "telegram_id", 0))
	if tgid <= 0 {
		failWithCode(w, http.StatusBadRequest, ErrTGIDInvalid, "telegram_id 无效")
		return
	}
	// BindUserTelegramAtomic 在同一把写锁里做唯一性 + admin 自保 + 写入，
	// 替换旧实现里 FindUserByTelegramID(RLock) → UpdateUser(Lock) 两段独立锁，
	// 关闭并发同 telegram_id 绑定到两个 UID 的 TOCTOU 窗口。
	u, old, err := a.store().BindUserTelegramAtomic(uid, tgid, current(r).User.UID)
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			// store.ErrConflict 同时承载两类语义：目标是其他 admin 不允许改写，
			// 或 telegram_id 已被占用。优先识别后者（语义更精确）。
			if existing, okUser := a.store().FindUserByTelegramID(tgid); okUser && existing.UID != uid {
				failWithCode(w, http.StatusConflict, ErrTGIDTaken, "Telegram ID is already bound to another user")
				return
			}
		}
		if statusFromError(w, err) {
			return
		}
	}
	ok(w, "Telegram bound", map[string]any{"uid": u.UID, "username": u.Username, "telegram_id": u.TelegramID, "old_telegram_id": zeroNil(old)})
}

func (a *App) handleUserByTelegram(w http.ResponseWriter, r *http.Request, params Params) {
	tgid, _ := int64Param(params, "telegram_id")
	if u, found := a.store().FindUserByTelegramID(tgid); found {
		ok(w, "OK", publicUser(u))
		return
	}
	failWithCode(w, http.StatusNotFound, ErrUserNotFound, userNotFoundMessage)
}

func (a *App) handleCountZero(w http.ResponseWriter, r *http.Request, _ Params) {
	result := a.cleanupUnusedUploadAssets(24 * time.Hour)
	ok(w, "OK", map[string]any{"count": result["deleted"], "cleaned": result["deleted"], "scanned": result["scanned"], "failed": result["failed"]})
}

func (a *App) handleAdminBindEmby(w http.ResponseWriter, r *http.Request, params Params) {
	// 显式 admin 断言。AuthAdmin 路由（routes.go:177）已挡住非 admin，但 admin
	// 强力 mutating handler 必须自己再确认一次：未来若有人把这个 handler 同
	// 时挂到 AuthUser 路由（手抖 / 复制粘贴），dispatcher 不会拦下，handler
	// 这一行会。
	if requireAdmin(w, r) {
		return
	}
	targetUID, _ := int64Param(params, "uid")
	body := decodeMap(r)
	embyIDInput := stringValue(body, "emby_id")
	embyNameInput := stringValue(body, "emby_username")
	force := boolValue(body, "force", false)
	var remoteUser map[string]any
	var found bool
	var lookupErr error
	if embyIDInput != "" {
		remoteUser, found, lookupErr = a.embyUserByID(r.Context(), embyIDInput)
	} else {
		remoteUser, found, lookupErr = a.embyUserByName(r.Context(), embyNameInput)
	}
	if lookupErr != nil {
		failWithCode(w, http.StatusBadGateway, ErrEmbyUserLookupFailed, "failed to read Emby user")
		return
	}
	if !found {
		failWithCode(w, http.StatusNotFound, ErrEmbyUserNotFound, "Emby user not found")
		return
	}
	embyID := asString(remoteUser["Id"])
	embyName := firstNonEmpty(asString(remoteUser["Name"]), embyNameInput, embyID)
	updatedUser, displacedUID, updateErr := a.store().BindUserEmbyAtomicWithUpdate(targetUID, embyID, embyName, force, func(u *store.User, before store.User) error {
		a.consumePendingEmbyEntitlementOnBind(u, before)
		return nil
	})
	if errors.Is(updateErr, store.ErrConflict) {
		existing, _ := a.store().FindUserByEmbyID(embyID)
		// 旧实现走 ok() 200 + {"conflict": true, ...}：前端只能依赖隐式
		// 约定查 data.conflict，与其他 admin handler 的"重名/已存在"统一
		// 走 409 + ErrCode 不一致。改为 failWithCodeData：envelope
		// success=false + code=EMBY_ACCOUNT_CONFLICT + 同样的 conflict 元
		// 数据。前端用 errorCode 判定即可，无需再读 data.conflict。
		failWithCodeData(w, http.StatusConflict, ErrEmbyAccountConflict, "Emby account already linked", map[string]any{
			"conflict_uid":      existing.UID,
			"conflict_username": existing.Username,
			"emby_id":           embyID,
			"emby_username":     embyName,
		})
		return
	}
	if statusFromError(w, updateErr) {
		return
	}
	_ = a.embyApplyEnabledState(r.Context(), updatedUser.UID, updatedUser.EmbyID, a.embyShouldEnableUser(updatedUser))
	previousUID := any(nil)
	if displacedUID != 0 {
		previousUID = displacedUID
	}
	ok(w, "Emby account linked", map[string]any{"uid": updatedUser.UID, "emby_id": updatedUser.EmbyID, "emby_username": updatedUser.EmbyUsername, "force_taken": displacedUID != 0, "previous_uid": previousUID, "user": publicUser(updatedUser)})
}

func (a *App) handleTelegramRosterStats(w http.ResponseWriter, r *http.Request, _ Params) {
	chats := telegramChatIDs(a.cfg().TelegramGroupIDs)
	chatID := ""
	if len(chats) > 0 {
		chatID = chats[0]
	}
	stats, err := a.store().TelegramRosterStats(chatID)
	if err != nil {
		fail(w, http.StatusInternalServerError, "读取 Telegram 花名册统计失败")
		return
	}
	entries, err := a.store().TelegramRoster(chatID, true)
	if err != nil {
		fail(w, http.StatusInternalServerError, "读取 Telegram 花名册失败")
		return
	}
	bound := 0
	unbound := 0
	if len(entries) > 0 {
		for _, entry := range entries {
			if entry.IsBot {
				continue
			}
			if _, okUser := a.store().FindUserByTelegramID(entry.TelegramID); okUser {
				bound++
			} else {
				unbound++
			}
		}
	} else {
		for _, u := range a.store().ListUsers() {
			if u.TelegramID == 0 {
				continue
			}
			bound++
		}
		stats["total"] = bound
		stats["active"] = bound
		stats["known_only"] = true
	}
	stats["bound"] = bound
	stats["unbound"] = unbound
	ok(w, "OK", stats)
}
