package api

import "net/http"

// registerV2Routes keeps the native SSR resource contract separate from the
// legacy compatibility inventory. V1 remains registered below for rollback
// and external clients; V2 pages must prefer this collection as it grows.
func (a *App) registerV2Routes() {
	a.add(http.MethodGet, "/api/v2/system/health", AuthPublic, a.handleV2Health)
	a.add(http.MethodGet, "/api/v2/system/capabilities", AuthPublic, a.handleV2Capabilities)
	a.add(http.MethodPost, "/api/v2/auth/login", AuthPublic, a.handleV2Login)
	a.add(http.MethodPost, "/api/v2/auth/login/apikey", AuthPublic, a.handleV2LoginByAPIKey)
	a.add(http.MethodPost, "/api/v2/auth/login/telegram", AuthPublic, a.handleV2TelegramLogin)
	a.add(http.MethodGet, "/api/v2/auth/me", AuthUser, a.handleV2CurrentUser)
	a.add(http.MethodPost, "/api/v2/auth/logout", AuthUser, a.handleV2Logout)
	a.add(http.MethodPost, "/api/v2/auth/logout/all", AuthUser, a.handleV2LogoutAll)
	a.add(http.MethodPost, "/api/v2/auth/refresh", AuthUser, a.handleV2RefreshSession)
	a.add(http.MethodPost, "/api/v2/auth/password/emby", AuthPublic, a.handleV2ForgotPasswordByEmby)
	a.add(http.MethodPost, "/api/v2/auth/password/email/request", AuthPublic, a.handleV2EmailPasswordResetRequest)
	a.add(http.MethodPost, "/api/v2/auth/password/email/reset", AuthPublic, a.handleV2EmailPasswordReset)
	a.add(http.MethodPost, "/api/v2/registration", AuthPublic, a.handleV2Register)
	a.add(http.MethodGet, "/api/v2/registration/availability", AuthPublic, a.handleV2RegistrationAvailability)
	a.add(http.MethodPost, "/api/v2/registration/telegram/bind-code", AuthPublic, a.handleV2CreateRegistrationBindCode)
	a.add(http.MethodGet, "/api/v2/dashboard/summary", AuthUser, a.handleV2DashboardSummary)
	a.add(http.MethodGet, "/api/v2/settings", AuthUser, a.handleV2UserSettings)
	a.add(http.MethodPut, "/api/v2/settings/preferences", AuthUser, a.handleV2UpdateUserSettings)
	a.add(http.MethodGet, "/api/v2/settings/appearance", AuthUser, a.handleV2UserAppearance)
	a.add(http.MethodPut, "/api/v2/settings/appearance/background", AuthUser, a.handleV2UpdateUserBackground)
	a.add(http.MethodDelete, "/api/v2/settings/appearance/background", AuthUser, a.handleV2DeleteUserBackground)
	a.add(http.MethodPost, "/api/v2/settings/appearance/background/upload", AuthUser, a.handleV2UploadUserBackground)
	a.add(http.MethodPost, "/api/v2/settings/appearance/avatar/upload", AuthUser, a.handleV2UploadUserAvatar)
	a.add(http.MethodDelete, "/api/v2/settings/appearance/avatar", AuthUser, a.handleV2DeleteUserAvatar)
	a.add(http.MethodPost, "/api/v2/settings/email/send-code", AuthUser, a.handleV2SendEmailCode)
	a.add(http.MethodPost, "/api/v2/settings/email/verify", AuthUser, a.handleV2VerifyEmailCode)
	a.add(http.MethodPost, "/api/v2/settings/password/system", AuthUser, a.handleV2ChangePassword)
	a.add(http.MethodPost, "/api/v2/settings/password/emby", AuthUser, a.handleV2ChangeEmbyPassword)
	a.add(http.MethodPost, "/api/v2/settings/emby/bind", AuthUser, a.handleV2BindEmby)
	a.add(http.MethodPost, "/api/v2/settings/emby/register", AuthUser, a.handleV2RegisterEmby)
	a.add(http.MethodPost, "/api/v2/settings/emby/unbind", AuthUser, a.handleV2UnbindEmby)
	a.add(http.MethodGet, "/api/v2/settings/apikeys", AuthUser, a.handleV2ListAPIKeys)
	a.add(http.MethodPost, "/api/v2/settings/apikeys", AuthUser, a.handleV2CreateAPIKey)
	a.add(http.MethodPut, "/api/v2/settings/apikeys/:key_id", AuthUser, a.handleV2UpdateAPIKey)
	a.add(http.MethodDelete, "/api/v2/settings/apikeys/:key_id", AuthUser, a.handleV2DeleteAPIKey)
	a.add(http.MethodGet, "/api/v2/announcements", AuthUser, a.handleV2Announcements)
	a.add(http.MethodPost, "/api/v2/announcements/ack", AuthUser, a.handleV2AckAnnouncements)
	a.add(http.MethodGet, "/api/v2/signin/summary", AuthUser, a.handleV2SigninSummary)
	a.add(http.MethodPost, "/api/v2/signin", AuthUser, a.handleV2Signin)
	a.add(http.MethodPost, "/api/v2/signin/renew", AuthUser, a.handleV2SigninRenew)
	a.add(http.MethodPut, "/api/v2/signin/preferences", AuthUser, a.handleV2SigninPreferences)
	a.add(http.MethodGet, "/api/v2/invite/summary", AuthUser, a.handleV2InviteSummary)
	a.add(http.MethodPost, "/api/v2/invite/codes", AuthUser, a.handleV2CreateInviteCode)
	a.add(http.MethodPost, "/api/v2/invite/renew-codes", AuthUser, a.handleV2CreateInviteCode)
	a.add(http.MethodDelete, "/api/v2/invite/codes/:code", AuthUser, a.handleV2DeleteInviteCode)
	a.add(http.MethodPost, "/api/v2/invite/children/:uid/detach-expired", AuthUser, a.handleV2DetachExpiredInviteChild)
	a.add(http.MethodPost, "/api/v2/invite/me/detach-expired", AuthUser, a.handleV2DetachMyExpiredInvite)
	a.add(http.MethodGet, "/api/v2/bangumi/summary", AuthUser, a.handleV2BangumiSummary)
	a.add(http.MethodPost, "/api/v2/bangumi/sync", AuthUser, a.handleV2BangumiSync)
	a.add(http.MethodDelete, "/api/v2/bangumi/sync/history", AuthUser, a.handleV2BangumiClearHistory)
	a.add(http.MethodPut, "/api/v2/bangumi/preferences", AuthUser, a.handleV2BangumiPreferences)
	a.add(http.MethodGet, "/api/v2/bangumi/collections", AuthUser, a.handleV2BangumiCollections)
	a.add(http.MethodPatch, "/api/v2/bangumi/collections/:subject_id", AuthUser, a.handleV2UpdateBangumiCollection)
	a.add(http.MethodGet, "/api/v2/admin/bangumi/users", AuthAdmin, a.handleV2AdminBangumiUsers)
	a.add(http.MethodGet, "/api/v2/admin/bangumi/users/:uid/records", AuthAdmin, a.handleV2AdminBangumiRecords)
	a.add(http.MethodPost, "/api/v2/admin/bangumi/users/:uid/sync", AuthAdmin, a.handleV2AdminBangumiSync)
	a.add(http.MethodGet, "/api/v2/admin/bangumi/users/:uid/logs", AuthAdmin, a.handleV2AdminBangumiLogs)
	a.add(http.MethodDelete, "/api/v2/admin/bangumi/users/:uid/logs", AuthAdmin, a.handleV2AdminBangumiClearLogs)
	a.add(http.MethodGet, "/api/v2/admin/announcements", AuthAdmin, a.handleV2AdminAnnouncements)
	a.add(http.MethodPost, "/api/v2/admin/announcements", AuthAdmin, a.handleV2CreateAnnouncement)
	a.add(http.MethodPut, "/api/v2/admin/announcements/:announcement_id", AuthAdmin, a.handleV2UpdateAnnouncement)
	a.add(http.MethodDelete, "/api/v2/admin/announcements/:announcement_id", AuthAdmin, a.handleV2DeleteAnnouncement)
	a.add(http.MethodGet, "/api/v2/admin/audit-logs", AuthAdmin, a.handleV2ListAuditLogs)
	a.add(http.MethodDelete, "/api/v2/admin/audit-logs/:log_id", AuthAdmin, a.handleV2DeleteAuditLog)
	a.add(http.MethodPost, "/api/v2/admin/audit-logs/clear", AuthAdmin, a.handleV2ClearAuditLogs)
	a.add(http.MethodPost, "/api/v2/admin/audit-logs/prune", AuthAdmin, a.handleV2PruneAuditLogs)
	a.add(http.MethodGet, "/api/v2/admin/invite/tree", AuthAdmin, a.handleV2AdminInviteTree)
	a.add(http.MethodGet, "/api/v2/admin/invite/codes", AuthAdmin, a.handleV2AdminInviteCodes)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/:uid/detach", AuthAdmin, a.handleV2AdminInviteDetach)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/:uid/detach-delete-emby", AuthAdmin, a.handleV2AdminInviteDetachDeleteEmby)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/detach-batch", AuthAdmin, a.handleV2AdminInviteDetachBatch)
	a.add(http.MethodPost, "/api/v2/admin/invite/quick-maintenance", AuthAdmin, a.handleV2AdminInviteQuickMaintenance)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/:uid/disable", AuthAdmin, a.handleV2AdminInviteToggleUser)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/:uid/enable", AuthAdmin, a.handleV2AdminInviteToggleUser)
	a.add(http.MethodPost, "/api/v2/admin/invite/users/:uid/delete", AuthAdmin, a.handleV2AdminInviteDeleteUser)
	a.add(http.MethodGet, "/api/v2/admin/invite/config/schema", AuthAdmin, a.handleV2AdminInviteConfigSchema)
	a.add(http.MethodPut, "/api/v2/admin/invite/config/schema", AuthAdmin, a.handleV2AdminInviteConfigSchema)
	a.add(http.MethodGet, "/api/v2/admin/media-requests", AuthAdmin, a.handleV2AdminMediaRequests)
	a.add(http.MethodPut, "/api/v2/admin/media-requests/:request_id", AuthAdmin, a.handleV2UpdateMediaRequestStatus)
	a.add(http.MethodDelete, "/api/v2/admin/media-requests/:request_id", AuthAdmin, a.handleV2DeleteMediaRequest)
	a.add(http.MethodPut, "/api/v2/admin/media-requests/by-key/:require_key", AuthAdmin, a.handleV2UpdateMediaRequestByKey)
	a.add(http.MethodPut, "/api/v2/admin/media-requests/batch", AuthAdmin, a.handleV2UpdateMediaRequestsByKey)
	a.add(http.MethodPut, "/api/v2/admin/media-requests/batch/by-key", AuthAdmin, a.handleV2UpdateMediaRequestsByKey)
	a.add(http.MethodDelete, "/api/v2/admin/media-requests/by-key/:require_key", AuthAdmin, a.handleV2DeleteMediaRequestByKey)

	// Admin ticket resources back the SSR queue and conversation page. Keep
	// attachments inside the same protected resource family so rendered URLs
	// cannot accidentally fall back to a legacy browser-side request.
	a.add(http.MethodGet, "/api/v2/admin/tickets", AuthAdmin, a.handleV2AdminTickets)
	a.add(http.MethodGet, "/api/v2/admin/tickets/:ticket_id", AuthAdmin, a.handleV2AdminTicket)
	a.add(http.MethodPatch, "/api/v2/admin/tickets/:ticket_id", AuthAdmin, a.handleAdminUpdateTicket)
	a.add(http.MethodPost, "/api/v2/admin/tickets/:ticket_id/replies", AuthAdmin, a.handleAdminReplyTicket)
	a.add(http.MethodDelete, "/api/v2/admin/tickets/:ticket_id", AuthAdmin, a.handleAdminDeleteTicket)
	a.add(http.MethodPost, "/api/v2/admin/tickets/:ticket_id/attachments", AuthAdmin, a.handleUploadTicketImage)
	a.add(http.MethodGet, "/api/v2/admin/tickets/:ticket_id/attachments/:filename", AuthAdmin, a.handleGetTicketImage)
	a.add(http.MethodDelete, "/api/v2/admin/tickets/:ticket_id/attachments/:filename", AuthAdmin, a.handleDeleteTicketImage)
	a.add(http.MethodGet, "/api/v2/admin/ticket-types", AuthAdmin, a.handleV2AdminTicketTypes)
	a.add(http.MethodPost, "/api/v2/admin/ticket-types", AuthAdmin, a.handleAdminAddTicketType)
	a.add(http.MethodPatch, "/api/v2/admin/ticket-types/:ticket_type", AuthAdmin, a.handleV2AdminRenameTicketType)
	a.add(http.MethodDelete, "/api/v2/admin/ticket-types/:ticket_type", AuthAdmin, a.handleV2AdminDeleteTicketType)

	a.add(http.MethodGet, "/api/v2/admin/regcodes", AuthAdmin, a.handleV2AdminRegcodes)
	a.add(http.MethodPost, "/api/v2/admin/regcodes", AuthAdmin, a.handleV2CreateRegcodes)
	a.add(http.MethodPost, "/api/v2/admin/regcodes/batch-delete", AuthAdmin, a.handleV2BatchDeleteRegcodes)
	a.add(http.MethodGet, "/api/v2/admin/regcodes/:code", AuthAdmin, a.handleV2AdminRegcode)
	a.add(http.MethodPatch, "/api/v2/admin/regcodes/:code", AuthAdmin, a.handleV2UpdateRegcode)
	a.add(http.MethodDelete, "/api/v2/admin/regcodes/:code", AuthAdmin, a.handleV2DeleteRegcode)
	a.add(http.MethodGet, "/api/v2/admin/regcodes/:code/usage", AuthAdmin, a.handleV2AdminRegcodeUsage)
	a.add(http.MethodPost, "/api/v2/admin/regcodes/:code/usage/clear", AuthAdmin, a.handleV2ClearRegcodeUsage)

	// Administrator user resources. V1 remains available for rollback and
	// integrations; V2 uses an explicit items/pagination collection and keeps
	// all mutations behind the same audited handlers.
	a.add(http.MethodGet, "/api/v2/admin/users", AuthAdmin, a.handleV2AdminUsers)
	a.add(http.MethodPost, "/api/v2/admin/users", AuthAdmin, a.handleV2AdminCreateUser)
	a.add(http.MethodGet, "/api/v2/admin/users/:uid", AuthAdmin, a.handleV2AdminUser)
	a.add(http.MethodPut, "/api/v2/admin/users/:uid", AuthAdmin, a.handleV2AdminUpdateUser)
	a.add(http.MethodDelete, "/api/v2/admin/users/:uid", AuthAdmin, a.handleV2AdminDeleteUser)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/delete", AuthAdmin, a.handleV2AdminDeleteUser)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/disable", AuthAdmin, a.handleV2AdminToggleUser)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/enable", AuthAdmin, a.handleV2AdminToggleUser)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/emby/enable", AuthAdmin, a.handleV2AdminToggleEmby)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/emby/disable", AuthAdmin, a.handleV2AdminToggleEmby)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/force-unbind", AuthAdmin, a.handleV2AdminForceUnbind)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/registration-queue/clear", AuthAdmin, a.handleV2AdminRegistrationQueueClear)
	a.add(http.MethodPost, "/api/v2/admin/users/registration-queue/clear", AuthAdmin, a.handleV2AdminRegistrationQueueClear)
	a.add(http.MethodPost, "/api/v2/admin/users/registration-queue/grant-entitlement-and-clear", AuthAdmin, a.handleRegistrationEntitlementBulk)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/registration-entitlement", AuthAdmin, a.handleV2AdminRegistrationEntitlement)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/registration-entitlement/dequeue", AuthAdmin, a.handleV2AdminRegistrationEntitlement)
	a.add(http.MethodPost, "/api/v2/admin/users/sync-bindings", AuthAdmin, a.handleSyncBindings)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/refresh-status", AuthAdmin, a.handleV2AdminRefreshUserStatus)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/renew", AuthAdmin, a.handleV2AdminRenewUser)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/cancel-permanent", AuthAdmin, a.handleV2AdminSetUserExpiry)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/set-expiry", AuthAdmin, a.handleV2AdminSetUserExpiry)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/reset-password", AuthAdmin, a.handleV2AdminResetPassword)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/kick", AuthAdmin, a.handleV2AdminKickUser)
	a.add(http.MethodPut, "/api/v2/admin/users/:uid/admin", AuthAdmin, a.handleV2AdminSetRole)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/unbind-telegram", AuthAdmin, a.handleV2AdminUnbindTelegram)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/bind-telegram", AuthAdmin, a.handleV2AdminBindTelegram)
	a.add(http.MethodGet, "/api/v2/admin/users/by-telegram/:telegram_id", AuthAdmin, a.handleUserByTelegram)
	a.add(http.MethodPost, "/api/v2/admin/users/:uid/bind-emby", AuthAdmin, a.handleV2AdminBindEmby)

	// Emby management resources. Reads remain bounded and manual-refresh only;
	// mutations reuse the audited legacy handlers during the V2 migration.
	a.add(http.MethodGet, "/api/v2/admin/emby/users", AuthAdmin, a.handleV2AdminEmbyUsers)
	a.add(http.MethodGet, "/api/v2/admin/emby/device-audit", AuthAdmin, a.handleV2AdminEmbyDeviceAudit)
	a.add(http.MethodGet, "/api/v2/admin/emby/activity-logs", AuthAdmin, a.handleV2AdminEmbyActivityLogs)
	a.add(http.MethodPost, "/api/v2/admin/emby/activity-logs/sync", AuthAdmin, a.handleV2AdminEmbyActivityLogSync)
	a.add(http.MethodPost, "/api/v2/admin/emby/test", AuthAdmin, a.handleV2AdminEmbyConnectivityTest)
	a.add(http.MethodPost, "/api/v2/admin/emby/broadcast", AuthAdmin, a.handleV2AdminEmbyBroadcast)
	a.add(http.MethodPost, "/api/v2/admin/emby/sync", AuthAdmin, a.handleV2AdminEmbySync)
	a.add(http.MethodPost, "/api/v2/admin/emby/import-users", AuthAdmin, a.handleV2AdminEmbyImportUsers)
	a.add(http.MethodPost, "/api/v2/admin/emby/delete-unlinked", AuthAdmin, a.handleV2AdminEmbyDeleteUnlinked)
	a.add(http.MethodPost, "/api/v2/admin/emby/cleanup-orphans", AuthAdmin, a.handleV2AdminEmbyCleanupOrphans)
	a.add(http.MethodPost, "/api/v2/admin/emby/reset-bindings", AuthAdmin, a.handleV2AdminEmbyResetBindings)
	a.add(http.MethodPost, "/api/v2/admin/emby/create-standalone", AuthAdmin, a.handleV2AdminEmbyCreateStandalone)
	a.add(http.MethodPost, "/api/v2/admin/emby/force-set-password", AuthAdmin, a.handleV2AdminEmbyForceSetPassword)
	a.add(http.MethodPost, "/api/v2/admin/emby/users/:embyId/enable", AuthAdmin, a.handleV2AdminEmbyUserToggle)
	a.add(http.MethodPost, "/api/v2/admin/emby/users/:embyId/disable", AuthAdmin, a.handleV2AdminEmbyUserToggle)
	a.add(http.MethodPost, "/api/v2/admin/emby/users/:embyId/kick", AuthAdmin, a.handleV2AdminEmbyUserKick)
}
